spring:
  output:
    ansi:
      enabled: ALWAYS #to display colours
  profiles:
    active: default
  application:
    name: LOG-ANALYSIS-SERVICE
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
#    ;DB_CLOSE_DELAY=-1
#java -classpath ..\lib\hsqldb-jdk8.jar org.hsqldb.Server --database.0 test
    url: jdbc:hsqldb:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    password: 
    type: com.zaxxer.hikari.HikariDataSource
  hsql:
    console:
      enables: true
  jackson:
    default-property-inclusion: NON_EMPTY

logging:
  pattern:
    console: "%clr{%d{ISO8601}}{black} %highlight(%-5level) [%clr{%t}{blue}] %clr{%C{1.}}{yellow}: %msg%n%xThrowable"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: info
  file:
    name: ${spring.application.name}
    path: ./

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html # default   http://localhost:8080/api/v3/api-docs/swagger-config
    operationsSorter: method
    
# springdoc.swagger-ui.path=/swagger-ui/  <-- http://localhost:${port}/log-analysis-service/swagger-ui/ <-- swagger 3
#springdoc.swagger-ui.operations-sorter=method
#springdoc.swagger-ui.use-root-path=true
#springdoc.api-docs.path=/api-docs <-- http://localhost:${port}/log-analysis-service/api-docs/
#management.health.defaults.enabled=true
#management.endpoint.health.show-details=always <-- http://localhost:${port}/log-analysis-service/actuator/health
#management.health.ldap.enabled=false
